route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: 'huy.dang@gh.com'
    from: 'huy.dang@gh.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'huy.dang@gh.com'
    auth_identity: 'huy.dang@gh.com'
    auth_password: 'xxx-my-secret-xxx'

# global:
#   smtp_smarthost: 'localhost:25'
#   smtp_from: 'alertmanager@example.com'
# route:
#   receiver: example-email
# receivers:
# - name: example-email
#   email_configs:
#   - to: 'huysamdua86@gmail.com'

# global:
#   resolve_timeout: 5m

# route:
#   group_by: ['alertname']
#   group_wait: 10s
#   group_interval: 10s
#   repeat_interval: 1h
#   receiver: 'web.hook'
# receivers:
# - name: 'web.hook'
#   webhook_configs:
#   - url: 'http://127.0.0.1:5001/'
# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']
